version: "2"
services:
    db:
      container_name: db
      image: mysql
      ports:
       - "3306:3306"  
      environment:
         - MYSQL_ROOT_PASSWORD=1234
         - MYSQL_DATABASE=potato

      volumes:
         - /home/avi/Projects/potato-ads/db/mysql/data:/var/lib/mysql
         - /home/avi/Projects/potato-ads/db/mysql/init:/docker-entrypoint-initdb.d/:ro